### ISSUE TITLE
env.js is an anti-pattern

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/isomorphic-js-lib-template#2]
I think the env.js run-time environment detection code is an anti-pattern and should be avoided in most cases.  We statically know which platform is being used, so it's better to put platform specific code in separate files (ie, util.js and util-browser.js) and use package.js browser field to hint to webpack, and similar tools, to use the browser code for browsers.  Using the env.js pattern often results in "if(nodejs) { } else { }" code which requires special handling to ensure node polyfills and the node code itself are not included in the webpacked output.  Best to avoid that confusion.

**Comment by dmitrizagidulin** [comment]
@davidlehn Good point.

**Comment by dmitrizagidulin** [comment]
env.js has been removed, closing.
